const DENTIST_LEADS_PRESET = [
  {
    "id": "lead_1787225295709_1_9rl0",
    "firstName": "Varuna",
    "lastName": "Wadhwani",
    "title": "Dentist",
    "company": "123 Dentist",
    "rawCompany": "123 Dentist",
    "linkedinUrl": "https://www.linkedin.com/in/varuna-trivedi-a8a2a64b",
    "email": "vwadhwani@123dentist.com",
    "phone": "17789964867",
    "city": "",
    "state": "Vancouver",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295709_2_vavc",
    "firstName": "Allison",
    "lastName": "Blatt",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Margarita",
    "linkedinUrl": "https://www.linkedin.com/in/allison-blatt-25532b75",
    "email": "aliblatt@hotmail.com",
    "phone": "+14045586986",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295709_3_00hx",
    "firstName": "Arv",
    "lastName": "Sooch",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Cooper & Associates",
    "linkedinUrl": "https://www.linkedin.com/in/arv-sooch-49893141",
    "email": "kaizendental@telus.net",
    "phone": "+16042701341",
    "city": "Richmond",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295710_4_tdr3",
    "firstName": "Karim",
    "lastName": "Shivji",
    "title": "President",
    "company": "123 Dentist",
    "rawCompany": "123 dentist",
    "linkedinUrl": "https://www.linkedin.com/in/karim-shivji-031292101",
    "email": "kshivji@123dentist.com",
    "phone": "+16047653692",
    "city": "Coquitlam",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295710_5_xtj2",
    "firstName": "Dr",
    "lastName": "Glenn Neilson",
    "title": "General Dentist",
    "company": "your dental clinic",
    "rawCompany": "Cooper & Associates",
    "linkedinUrl": "https://www.linkedin.com/in/glenn-neilson-b2a518101",
    "email": "neilson@telus.net",
    "phone": "+17805397400",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295710_6_92g4",
    "firstName": "Sherwood",
    "lastName": "Sherwood Family Dental",
    "title": "General Dentist",
    "company": "your dental clinic",
    "rawCompany": "Diril Steel Co (Diril Demir Celik San. ve Tic. A.S.)",
    "linkedinUrl": "https://www.linkedin.com/in/sherwood-dental-658880110",
    "email": "sherwoodfamilydental@gmail.com",
    "phone": "+12507272273",
    "city": "Victoria",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295710_7_t4vd",
    "firstName": "Stuart",
    "lastName": "Katz",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Diril Steel Co (Diril Demir Celik San. ve Tic. A.S.)",
    "linkedinUrl": "https://www.linkedin.com/in/stuart-katz-44196b28",
    "email": "stukatz02@gmail.com",
    "phone": "16462919877",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_8_79lt",
    "firstName": "Mark",
    "lastName": "Bishara",
    "title": "Owner Dentist",
    "company": "your dental clinic",
    "rawCompany": "Diril Steel Co (Diril Demir Celik San. ve Tic. A.S.)",
    "linkedinUrl": "https://www.linkedin.com/in/mark-bishara-81253a1b",
    "email": "bbishara6@gmail.com",
    "phone": "+19059257559",
    "city": "Bowmanville",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_9_wl5h",
    "firstName": "Bobby",
    "lastName": "Brown",
    "title": "Dentist",
    "company": "Bobby Brown",
    "rawCompany": "bobby brown",
    "linkedinUrl": "https://www.linkedin.com/in/bobby-brown-23230718",
    "email": "bbrown@pga.com",
    "phone": "+15616248400",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_10_mz9e",
    "firstName": "William",
    "lastName": "Wei",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Margarita",
    "linkedinUrl": "https://www.linkedin.com/in/william-wei-493a09126",
    "email": "drwilliamwei@hotmail.com",
    "phone": "+14039756821",
    "city": "Calgary",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_11_1g0g",
    "firstName": "Bryant",
    "lastName": "Tomimoto",
    "title": "Dentist",
    "company": "Medicine Hat Construction Association",
    "rawCompany": "Medicine Hat Construction Association",
    "linkedinUrl": "https://www.linkedin.com/in/bryant-tomimoto-10728224",
    "email": "tomimoto@telusplanet.net",
    "phone": "+14032629455",
    "city": "Calgary",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_12_3imn",
    "firstName": "Hiroshi",
    "lastName": "Takagi",
    "title": "General Dentist",
    "company": "Coldwater Dental",
    "rawCompany": "Coldwater Dental",
    "linkedinUrl": "https://www.linkedin.com/in/hiroshi-takagi-575388108",
    "email": "dentaloffice@coldwaterdental.ca",
    "phone": "+17056863368",
    "city": "Coldwater",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_13_828w",
    "firstName": "Andreas",
    "lastName": "Azarko",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Diril Steel Co (Diril Demir Celik San. ve Tic. A.S.)",
    "linkedinUrl": "https://www.linkedin.com/in/andreas-azarko-3a885935",
    "email": "andreasazarko@gmail.com",
    "phone": "+17804837079",
    "city": "Edmonton",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_14_agdj",
    "firstName": "Henry",
    "lastName": "Choi",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Diril Steel Co (Diril Demir Celik San. ve Tic. A.S.)",
    "linkedinUrl": "https://www.linkedin.com/in/henry-choi-0848b586",
    "email": "henrychoi@gmail.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_15_m1xi",
    "firstName": "Aadil",
    "lastName": "Shamji",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Diril Steel Co (Diril Demir Celik San. ve Tic. A.S.)",
    "linkedinUrl": "https://www.linkedin.com/in/aadil-shamji-b4394262",
    "email": "aadilshamji@gmail.com",
    "phone": "+15196948030",
    "city": "Waterloo",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_16_y74q",
    "firstName": "Nancy",
    "lastName": "Schmidt",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Diril Steel Co (Diril Demir Celik San. ve Tic. A.S.)",
    "linkedinUrl": "https://www.linkedin.com/in/dr-nancy-schmidt-a648b149",
    "email": "nschmidt918@gmail.com",
    "phone": "+17702651626",
    "city": "Victoria",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_17_d3l3",
    "firstName": "James",
    "lastName": "Hennessy",
    "title": "Staff Dentist",
    "company": "Domain Office Search",
    "rawCompany": "Domain Office Search",
    "linkedinUrl": "https://www.linkedin.com/in/jameshennessycreative",
    "email": "info@domainofficesearch.com",
    "phone": "",
    "city": "Calgary",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_18_a2jd",
    "firstName": "David",
    "lastName": "Rushka",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Cooper & Associates",
    "linkedinUrl": "https://www.linkedin.com/in/dave-rushka-4307b382",
    "email": "dr_evil@telus.net",
    "phone": "+12503743353",
    "city": "Kamloops",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_19_ixb7",
    "firstName": "Saman",
    "lastName": "Samani",
    "title": "Associate Dentist",
    "company": "your dental clinic",
    "rawCompany": "Diril Steel Co (Diril Demir Celik San. ve Tic. A.S.)",
    "linkedinUrl": "https://www.linkedin.com/in/s-saman-samani-95b8444b",
    "email": "samanclinical@gmail.com",
    "phone": "",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_20_gdxo",
    "firstName": "Bruno",
    "lastName": "Pilon",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "Margarita",
    "linkedinUrl": "https://www.linkedin.com/in/bruno-pilon-730a5514",
    "email": "hollandlandingdental@hotmail.com",
    "phone": "+19058532400",
    "city": "East Gwillimbury",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_21_rs7z",
    "firstName": "Sarah",
    "lastName": "Jacobs",
    "title": "Dentist/Owner",
    "company": "Sarah Jacobs",
    "rawCompany": "sarah jacobs",
    "linkedinUrl": "https://www.linkedin.com/in/sarah-jacobs-50782828",
    "email": "w0404400@campus.nscc.ca",
    "phone": "",
    "city": "",
    "state": "Nova Scotia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_22_ergd",
    "firstName": "Carolyn",
    "lastName": "Macnutt",
    "title": "Dentist",
    "company": "Park West Dental Office",
    "rawCompany": "park west dental office",
    "linkedinUrl": "https://www.linkedin.com/in/carolyn-macnutt-756a1694",
    "email": "carolyn.macnutt@hotmail.com",
    "phone": "+19024577787",
    "city": "Halifax",
    "state": "Nova Scotia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_23_v0ly",
    "firstName": "Anna",
    "lastName": "Pranata",
    "title": "General Dentist",
    "company": "your dental clinic",
    "rawCompany": "Margarita",
    "linkedinUrl": "https://www.linkedin.com/in/anna-pranata-a52894104",
    "email": "annapranata@hotmail.com",
    "phone": "+16044171149",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_24_83by",
    "firstName": "George",
    "lastName": "Elias",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "People, Outlook Publishing",
    "linkedinUrl": "https://www.linkedin.com/in/george-elias-49286840",
    "email": "gelias84@outlook.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_25_i3gi",
    "firstName": "Albert",
    "lastName": "Voravong",
    "title": "General Dentist/Owner",
    "company": "your dental clinic",
    "rawCompany": "Diril Steel Co (Diril Demir Celik San. ve Tic. A.S.)",
    "linkedinUrl": "https://www.linkedin.com/in/albert-voravong-a38a6872",
    "email": "albertvoravong@gmail.com",
    "phone": "+17809514743",
    "city": "",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_26_mwhs",
    "firstName": "Kevin",
    "lastName": "Campbell",
    "title": "Dentist",
    "company": "Kevin Campbell",
    "rawCompany": "kevin campbell",
    "linkedinUrl": "https://www.linkedin.com/in/kevin-campbell-43139718",
    "email": "kevin.campbell1952@gmail.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_27_4km9",
    "firstName": "Paul",
    "lastName": "Coulombe",
    "title": "Retired Dentist",
    "company": "Zeus Systems",
    "rawCompany": "zeus systems inc",
    "linkedinUrl": "https://www.linkedin.com/in/paul-coulombe-63ab5592",
    "email": "pcoulombe@zeussystems.com",
    "phone": "",
    "city": "Brampton",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_28_zli3",
    "firstName": "Goran",
    "lastName": "Stanisavljevic",
    "title": "Pediatric Dentist, Business Proprietor",
    "company": "Crystal Dental Centre",
    "rawCompany": "crystal dental centre",
    "linkedinUrl": "https://www.linkedin.com/in/goran-stanisavljevic-3949b41b",
    "email": "goran@crystaldental.com",
    "phone": "",
    "city": "Burnaby",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_29_hlqz",
    "firstName": "Dhafir",
    "lastName": "Ali",
    "title": "Dentist",
    "company": "Clarenville Dental Care",
    "rawCompany": "clarenville dental care",
    "linkedinUrl": "https://www.linkedin.com/in/dhafir-ali-2237b72a",
    "email": "dhafirali@dental.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_30_p0cq",
    "firstName": "Deokhyun",
    "lastName": "Sung",
    "title": "Associate Dentist",
    "company": "Brightside Dental Care",
    "rawCompany": "brightside dental care",
    "linkedinUrl": "https://www.linkedin.com/in/deokhyun-sung-504973102",
    "email": "deokhyunsung@brightsidedentalcare.com",
    "phone": "",
    "city": "Winnipeg",
    "state": "Manitoba",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_31_dfhm",
    "firstName": "Salman",
    "lastName": "Jivani",
    "title": "Dentist",
    "company": "Dental Choice",
    "rawCompany": "dental choice",
    "linkedinUrl": "https://www.linkedin.com/in/salman-jivani-ab203965",
    "email": "salman@dentalchoice.ca",
    "phone": "",
    "city": "Edmonton",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_32_e6s0",
    "firstName": "Kristina",
    "lastName": "Pahuta",
    "title": "Associate Dentist",
    "company": "North Shores Dental",
    "rawCompany": "north shores dental",
    "linkedinUrl": "https://www.linkedin.com/in/kristina-pahuta-1a24a527",
    "email": "kristina@northshoresdental.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_33_2haw",
    "firstName": "Hedayat",
    "lastName": "Gorjestani",
    "title": "Canadian Board Certified Dentist",
    "company": "123 Dentist",
    "rawCompany": "123 Dentist",
    "linkedinUrl": "https://www.linkedin.com/in/hedayat-gorjestani-a9571564",
    "email": "hgorjestani@123dentist.com",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_34_p31s",
    "firstName": "Nibu",
    "lastName": "Varguise",
    "title": "Dentist",
    "company": "Paris Dental Centre",
    "rawCompany": "paris dental centre",
    "linkedinUrl": "https://www.linkedin.com/in/nibu-varguise-6b79197",
    "email": "nibu@parisdentalcentre.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_35_54f5",
    "firstName": "Ben",
    "lastName": "Rogala",
    "title": "General Dentist",
    "company": "Dental Choice",
    "rawCompany": "dental choice",
    "linkedinUrl": "https://www.linkedin.com/in/ben-rogala-35a05a59",
    "email": "ben@dentalchoice.ca",
    "phone": "",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_36_l0lj",
    "firstName": "Brett",
    "lastName": "Shkopich",
    "title": "General Dentist",
    "company": "Nuvo Dental",
    "rawCompany": "nuvo dental",
    "linkedinUrl": "https://www.linkedin.com/in/brett-shkopich-43152158",
    "email": "bshkopich@nuvodentalgroup.com",
    "phone": "",
    "city": "Saint Albert",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_37_3b48",
    "firstName": "John",
    "lastName": "Cameron",
    "title": "Dentist",
    "company": "Ottawa Heritage Dental  Kitchener Ontario",
    "rawCompany": "ottawa heritage dental  kitchener ontario",
    "linkedinUrl": "https://www.linkedin.com/in/dr-john-cameron-847baa43",
    "email": "jcameron@ottawaheritagedental.ca",
    "phone": "",
    "city": "Kitchener",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_38_4evm",
    "firstName": "Peter",
    "lastName": "Sbaraglia",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "selfemployed",
    "linkedinUrl": "https://www.linkedin.com/in/petersbaraglia",
    "email": "peter.sbaraglia@crystaldreamersrealm.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_39_nmk7",
    "firstName": "Leslie",
    "lastName": "Trains",
    "title": "General Dentist",
    "company": "your dental clinic",
    "rawCompany": "selfemployed",
    "linkedinUrl": "https://www.linkedin.com/in/leslie-trains-6584a9122",
    "email": "leslie.trains@crystaldreamersrealm.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_40_zxya",
    "firstName": "Ramanjot",
    "lastName": "Singh",
    "title": "Dentist",
    "company": "Private",
    "rawCompany": "private",
    "linkedinUrl": "https://www.linkedin.com/in/dr-ramanjot-singh-9a3600110",
    "email": "ramanjot@lesliestreet.cz",
    "phone": "",
    "city": "Thunder Bay",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295711_41_81hs",
    "firstName": "Jessica",
    "lastName": "Milne",
    "title": "Dentist",
    "company": "River Edge Family Dental",
    "rawCompany": "river edge family dental",
    "linkedinUrl": "https://www.linkedin.com/in/jessica-milne-908b96aa",
    "email": "jessica@riveredgedental.com",
    "phone": "",
    "city": "Sarnia",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_42_nuvx",
    "firstName": "Fozo",
    "lastName": "Sheen",
    "title": "Dentist",
    "company": "Canadian Dental Association",
    "rawCompany": "canadian dental association",
    "linkedinUrl": "https://www.linkedin.com/in/fozo-sheen-0586b270",
    "email": "fsheen@cda-adc.ca",
    "phone": "",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_43_ehfu",
    "firstName": "Danforth",
    "lastName": "Dental",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "converged digital networks",
    "linkedinUrl": "https://www.linkedin.com/in/danforth-neighbourhood-dental-b5b0a14b",
    "email": "ddental@dndc.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_44_7s1l",
    "firstName": "Scott",
    "lastName": "Kollen",
    "title": "Dentist",
    "company": "Royal Oak Dental",
    "rawCompany": "royal oak dental",
    "linkedinUrl": "https://www.linkedin.com/in/scott-kollen-3a2a9b59",
    "email": "scott@royaloakdental.co.nz",
    "phone": "",
    "city": "",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_45_5iqn",
    "firstName": "Robyn",
    "lastName": "Blatt",
    "title": "Dentist",
    "company": "Blatt Dental",
    "rawCompany": "blatt dental",
    "linkedinUrl": "https://www.linkedin.com/in/robyn-blatt-a1182259",
    "email": "drblatt@bellnet.ca",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_46_u4uf",
    "firstName": "Milica",
    "lastName": "Stamenkovic",
    "title": "Associate Dentist",
    "company": "Royal York Dental",
    "rawCompany": "royal york dental",
    "linkedinUrl": "https://www.linkedin.com/in/milica-stamenkovic-a2995bb",
    "email": "milica@royalyorkdental.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_47_zydj",
    "firstName": "Inderpreet",
    "lastName": "Brar",
    "title": "Dentist",
    "company": "Merivale Dental Centre",
    "rawCompany": "merivale dental centre",
    "linkedinUrl": "https://www.linkedin.com/in/inderpreet-brar-6057a46b",
    "email": "ibrar@merivaledentalcentre.com",
    "phone": "",
    "city": "Ottawa",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_48_xz50",
    "firstName": "Peter",
    "lastName": "Kiss",
    "title": "Dentist.",
    "company": "Kensington Dental Spa",
    "rawCompany": "kensington dental spa",
    "linkedinUrl": "https://www.linkedin.com/in/peter-kiss-b9653629",
    "email": "peter.kiss@kensingtondental.com",
    "phone": "",
    "city": "",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_49_qi2g",
    "firstName": "Betty",
    "lastName": "Mcveigh",
    "title": "Regional Manager",
    "company": "123 Dentist",
    "rawCompany": "123 Dentist",
    "linkedinUrl": "https://www.linkedin.com/in/betty-ann-mcveigh-250b8a8b",
    "email": "bmcveigh@123dentist.com",
    "phone": "",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_50_yy7f",
    "firstName": "Ekram",
    "lastName": "Moustafa",
    "title": "Dentist",
    "company": "Altima",
    "rawCompany": "altima",
    "linkedinUrl": "https://www.linkedin.com/in/ekram-moustafa-89830878",
    "email": "emoustafa@altima-agency.com",
    "phone": "",
    "city": "Brockville",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_51_9297",
    "firstName": "Longmei",
    "lastName": "Xu",
    "title": "Owner, Principle Dentist",
    "company": "Crystal Dental Centre",
    "rawCompany": "crystal dental centre",
    "linkedinUrl": "https://www.linkedin.com/in/longmei-xu-a9604670",
    "email": "longmei@crystaldental.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_52_4fav",
    "firstName": "Sandeep",
    "lastName": "Dhaliwal",
    "title": "Dentist",
    "company": "Dental Choice",
    "rawCompany": "dental choice",
    "linkedinUrl": "https://www.linkedin.com/in/sandeep-dhaliwal-71898b24",
    "email": "sdhaliwal@dentalchoice.ca",
    "phone": "",
    "city": "Edmonton",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_53_a9am",
    "firstName": "Mina",
    "lastName": "Y",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "selfemployed",
    "linkedinUrl": "https://www.linkedin.com/in/mina-y-6a032ba3",
    "email": "mina.y@crystaldreamersrealm.com",
    "phone": "",
    "city": "Edmonton",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_54_qtlu",
    "firstName": "Amy",
    "lastName": "Saray",
    "title": "Dentist",
    "company": "Merivale Dental Centre",
    "rawCompany": "merivale dental centre",
    "linkedinUrl": "https://www.linkedin.com/in/amy-saray-dds-12862633",
    "email": "asaray@merivaledentalcentre.com",
    "phone": "",
    "city": "Montreal",
    "state": "Quebec",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_55_zd9t",
    "firstName": "Marwan",
    "lastName": "Elaraby",
    "title": "Associate Dentist",
    "company": "Toothworks Canada",
    "rawCompany": "toothworks canada",
    "linkedinUrl": "https://www.linkedin.com/in/marwanaraby",
    "email": "marwan@toothworks.com",
    "phone": "",
    "city": "Mississauga",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_56_yi8q",
    "firstName": "Parveen",
    "lastName": "Azhar",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "ubc",
    "linkedinUrl": "https://www.linkedin.com/in/parveen-azhar-29b05113b",
    "email": "parveen@discoverunion.org",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_57_fesh",
    "firstName": "Miguel",
    "lastName": "Pohl",
    "title": "Dentist",
    "company": "Lakeside Dental",
    "rawCompany": "lakeside dental",
    "linkedinUrl": "https://www.linkedin.com/in/miguel-pohl-597610a3",
    "email": "miguel@lakesidedental.com",
    "phone": "",
    "city": "Edmonton",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_58_z6hq",
    "firstName": "Firoozeh",
    "lastName": "Samim",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "ubc",
    "linkedinUrl": "https://www.linkedin.com/in/firoozeh-samim-82017362",
    "email": "firoozeh@discoverunion.org",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_59_uie3",
    "firstName": "Angie",
    "lastName": "Banh",
    "title": "Owner, Dentist",
    "company": "Centre Dentaire De Gatineau",
    "rawCompany": "centre dentaire de gatineau",
    "linkedinUrl": "https://www.linkedin.com/in/angie-banh-2aab5045",
    "email": "angie.banh@cdentairegatineau.com",
    "phone": "",
    "city": "Gatineau",
    "state": "Quebec",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_60_d51p",
    "firstName": "Robert",
    "lastName": "Ganske",
    "title": "Dentist",
    "company": "Holland Cross Dental Centre",
    "rawCompany": "holland cross dental centre",
    "linkedinUrl": "https://www.linkedin.com/in/robert-ganske-a0409a7a",
    "email": "robert@hollandcrossdental.com",
    "phone": "",
    "city": "Ottawa",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_61_50jw",
    "firstName": "Katie",
    "lastName": "Fisher",
    "title": "Dentist",
    "company": "123 Dentist",
    "rawCompany": "123 Dentist",
    "linkedinUrl": "https://www.linkedin.com/in/katie-fisher-cpa-ca-09157141",
    "email": "kfisher@123dentist.com",
    "phone": "",
    "city": "",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_62_288x",
    "firstName": "Ally",
    "lastName": "Kassam",
    "title": "Dentist",
    "company": "Inspire Dental Group",
    "rawCompany": "inspire dental group",
    "linkedinUrl": "https://www.linkedin.com/in/ally-kassam-a8475349",
    "email": "akassam@inspiredental.ca",
    "phone": "",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_63_ek3i",
    "firstName": "Ran",
    "lastName": "Midroni",
    "title": "Dentist, Dental Anaesthetist",
    "company": "Village Family Dental Care",
    "rawCompany": "village family dental care",
    "linkedinUrl": "https://www.linkedin.com/in/ran-midroni-2968b124",
    "email": "rmidroni@vfdental.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_64_sz4u",
    "firstName": "Maria",
    "lastName": "Gagiu",
    "title": "Dentist",
    "company": "Indigo Public Affairs",
    "rawCompany": "indigo public affairs ltd",
    "linkedinUrl": "https://www.linkedin.com/in/maria-gagiu-70938aa8",
    "email": "maria.gagiu@thorncliffe.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_65_nwjs",
    "firstName": "Barry",
    "lastName": "Walkiewicz",
    "title": "Dentist",
    "company": "Royal Oak Dental",
    "rawCompany": "royal oak dental",
    "linkedinUrl": "https://www.linkedin.com/in/barry-walkiewicz-3476a927",
    "email": "barry@royaloakdental.co.nz",
    "phone": "",
    "city": "",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_66_kuur",
    "firstName": "Elysia",
    "lastName": "Lam",
    "title": "General Dentist",
    "company": "Boundary Trails Dental Corporation",
    "rawCompany": "boundary trails dental corporation",
    "linkedinUrl": "https://www.linkedin.com/in/elysia-lam-a8a36114a",
    "email": "elysia@boundarytrails.com",
    "phone": "",
    "city": "Morden",
    "state": "Manitoba",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_67_63nr",
    "firstName": "Ryan",
    "lastName": "Rakowski",
    "title": "Dentist",
    "company": "Fairview Dental Group",
    "rawCompany": "fairview dental group",
    "linkedinUrl": "https://www.linkedin.com/in/dr-ryan-rakowski-6614849",
    "email": "ryan@fairviewdental.ca",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295712_68_0pzy",
    "firstName": "Deepal",
    "lastName": "Bhambra",
    "title": "Dentist",
    "company": "Bluesmile",
    "rawCompany": "bluesmile",
    "linkedinUrl": "https://www.linkedin.com/in/deepal-bhambra-8317aa67",
    "email": "deepal.bhambra@bluesmile.eu",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295713_69_80ry",
    "firstName": "Zahir",
    "lastName": "Damji",
    "title": "Dentist",
    "company": "Dental Choice",
    "rawCompany": "dental choice",
    "linkedinUrl": "https://www.linkedin.com/in/zahir-damji-290a3327",
    "email": "zahir@dentalchoice.ca",
    "phone": "",
    "city": "Calgary",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295713_70_6s53",
    "firstName": "Raj",
    "lastName": "Sivendra",
    "title": "Dentist",
    "company": "Dsg Parkway Dental Lab",
    "rawCompany": "dsg parkway dental lab inc",
    "linkedinUrl": "https://www.linkedin.com/in/raj-sivendra-3928717a",
    "email": "rsivendra@parkwaydentallab.net",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295713_71_4fsy",
    "firstName": "Massoud",
    "lastName": "Aghakhani",
    "title": "Dentist",
    "company": "My Dental Clinic",
    "rawCompany": "my dental clinic",
    "linkedinUrl": "https://www.linkedin.com/in/massoud-aghakhani-4440a0a0",
    "email": "massoud.aghakhani@mydc.com.tr",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295713_72_6s1h",
    "firstName": "Bernard",
    "lastName": "Jin",
    "title": "Dentist",
    "company": "Hiossen Implant Canada",
    "rawCompany": "hiossen implant canada inc",
    "linkedinUrl": "https://www.linkedin.com/in/bernard-jin-0801ba32",
    "email": "bernard@hiossen.ca",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295713_73_f5t1",
    "firstName": "Nastaran",
    "lastName": "Heidari",
    "title": "Dentist",
    "company": "Riverstone Dental Care",
    "rawCompany": "riverstone dental care",
    "linkedinUrl": "https://www.linkedin.com/in/nastaran-heidari-6850813a",
    "email": "nastaran@riverstonedental.com",
    "phone": "",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295713_74_q7ae",
    "firstName": "Melanie",
    "lastName": "Little",
    "title": "General Dentist",
    "company": "Mint Dentistry",
    "rawCompany": "mint dentistry",
    "linkedinUrl": "https://www.linkedin.com/in/melanielittledentist",
    "email": "melanielittle@mintdentistry.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295713_75_2gyr",
    "firstName": "Navjot",
    "lastName": "Dhillon",
    "title": "General Dentist",
    "company": "Boundary Trails Dental Corporation",
    "rawCompany": "boundary trails dental corporation",
    "linkedinUrl": "https://www.linkedin.com/in/navjot-dhillon-a2344738",
    "email": "navjot@boundarytrails.com",
    "phone": "",
    "city": "",
    "state": "Manitoba",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295714_76_g5xf",
    "firstName": "Yvan",
    "lastName": "Latour",
    "title": "General Dentist",
    "company": "Lakeshore Dental Care",
    "rawCompany": "lakeshore dental care",
    "linkedinUrl": "https://www.linkedin.com/in/yvan-latour-60812477",
    "email": "yvan@lakeshoredentalcare.ca",
    "phone": "",
    "city": "North Bay",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295714_77_xzv3",
    "firstName": "Imtiaz",
    "lastName": "Kassam",
    "title": "Vp Operations",
    "company": "123 Dentist",
    "rawCompany": "123 dentist",
    "linkedinUrl": "https://www.linkedin.com/in/imtiaz-kassam-435519b3",
    "email": "ikassam@123dentist.com",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295714_78_d028",
    "firstName": "Qingqing",
    "lastName": "Liu",
    "title": "Student Dentist",
    "company": "your dental clinic",
    "rawCompany": "ubc",
    "linkedinUrl": "https://www.linkedin.com/in/qingqing-liu-a9220541",
    "email": "qingqing@discoverunion.org",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295714_79_7g3u",
    "firstName": "John",
    "lastName": "Mcgaw",
    "title": "General Dentist",
    "company": "Driftwood Dental",
    "rawCompany": "driftwood dental",
    "linkedinUrl": "https://www.linkedin.com/in/dr-john-mcgaw-83514b20",
    "email": "john@driftwooddental.com",
    "phone": "",
    "city": "",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295714_80_qlf9",
    "firstName": "Mairead",
    "lastName": "Loughlin",
    "title": "Associate Dentist",
    "company": "Great Slave Dental Clinic",
    "rawCompany": "great slave dental clinic",
    "linkedinUrl": "https://www.linkedin.com/in/dr-mairead-mc-loughlin-17b025bb",
    "email": "mairead@greatslavedental.com",
    "phone": "",
    "city": "Yellowknife",
    "state": "Northwest Territories",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295714_81_81cx",
    "firstName": "Fann",
    "lastName": "Amawi",
    "title": "Dentist",
    "company": "Groupe Parima",
    "rawCompany": "groupe parima inc",
    "linkedinUrl": "https://www.linkedin.com/in/fann-amawi-7689ba78",
    "email": "famawi@groupeparima.com",
    "phone": "",
    "city": "Montreal",
    "state": "Quebec",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295714_82_nwb4",
    "firstName": "Martin",
    "lastName": "Szczutkowski",
    "title": "Cosmetic And General Dentist",
    "company": "Queen Street Dental",
    "rawCompany": "queen street dental",
    "linkedinUrl": "https://www.linkedin.com/in/martin-szczutkowski-94a16944",
    "email": "mszczutkowski@queenstreetdental.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_83_7oj3",
    "firstName": "Jasmine",
    "lastName": "Sethi",
    "title": "General Dentist",
    "company": "123 Dentist",
    "rawCompany": "123 dentist",
    "linkedinUrl": "https://www.linkedin.com/in/jasmine-sethi-b3a014117",
    "email": "jsethi@123dentist.com",
    "phone": "",
    "city": "Burnaby",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_84_t6v2",
    "firstName": "Elisabeth",
    "lastName": "Chartier",
    "title": "Dentist",
    "company": "Carrefour Dentaire De Montreal",
    "rawCompany": "carrefour dentaire de montreal",
    "linkedinUrl": "https://www.linkedin.com/in/elisabeth-caron-chartier-55b7608a",
    "email": "elisabeth.chartier@carrefourdentaire.com",
    "phone": "",
    "city": "Longueuil",
    "state": "Quebec",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_85_2qoc",
    "firstName": "Natalia",
    "lastName": "Lavrov",
    "title": "Certified Dental Assistant",
    "company": "123 Dentist",
    "rawCompany": "123 Dentist",
    "linkedinUrl": "https://www.linkedin.com/in/natalia-lavrov-141b617a",
    "email": "nlavrov@123dentist.com",
    "phone": "",
    "city": "Surrey",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_86_mc0v",
    "firstName": "Susan",
    "lastName": "Huxtable",
    "title": "Dentist",
    "company": "Dr Susan Huxtable",
    "rawCompany": "dr susan huxtable",
    "linkedinUrl": "https://www.linkedin.com/in/susan-huxtable-a15b1092",
    "email": "shuxtable@drsusanhuxtable.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_87_kq2g",
    "firstName": "Sol",
    "lastName": "Weiss",
    "title": "Cosmetic Dentist / Owner",
    "company": "Art Of Dentistry",
    "rawCompany": "art of dentistry",
    "linkedinUrl": "https://www.linkedin.com/in/sol-weiss-92252132",
    "email": "sol@artofdentistry.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_88_ntt7",
    "firstName": "Shayma",
    "lastName": "Alaldabagh",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "selfemployed",
    "linkedinUrl": "https://www.linkedin.com/in/shayma-alaldabagh-824a99116",
    "email": "shayma.alaldabagh@crystaldreamersrealm.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_89_xk2y",
    "firstName": "Novinder",
    "lastName": "Singh",
    "title": "Dentist",
    "company": "Toothworks Canada",
    "rawCompany": "toothworks canada",
    "linkedinUrl": "https://www.linkedin.com/in/novinder-singh-560304121",
    "email": "novinder@toothworks.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_90_xkja",
    "firstName": "Arzoo",
    "lastName": "Singh",
    "title": "Dentist",
    "company": "Gdc",
    "rawCompany": "gdc",
    "linkedinUrl": "https://www.linkedin.com/in/arzoo-singh-109653113",
    "email": "arzoo@gdc.agency",
    "phone": "",
    "city": "Richmond",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_91_svq4",
    "firstName": "Andrea",
    "lastName": "Gelinas",
    "title": "General Dentist",
    "company": "Chrysalis Dental Centres",
    "rawCompany": "chrysalis dental centres",
    "linkedinUrl": "https://www.linkedin.com/in/dr-andrea-gelinas-7b3696b5",
    "email": "andrea.gelinas@dentalimplants123.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_92_z4c9",
    "firstName": "Julia",
    "lastName": "Ratkay",
    "title": "Dentist",
    "company": "Grandview Corners Dental And Wellness Centre",
    "rawCompany": "grandview corners dental and wellness centre",
    "linkedinUrl": "https://www.linkedin.com/in/julia-ratkay-93265124",
    "email": "jratkay@grandviewcornersdental.com",
    "phone": "",
    "city": "Langley",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_93_qpl7",
    "firstName": "Richard",
    "lastName": "Carr",
    "title": "Dentist",
    "company": "Liberty Village Dental",
    "rawCompany": "liberty village dental",
    "linkedinUrl": "https://www.linkedin.com/in/dr-richard-carr-1b713224",
    "email": "richard@libertyvillagedental.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_94_bk0a",
    "firstName": "Lauren",
    "lastName": "Davies",
    "title": "Dentist",
    "company": "Brightside Dental Care",
    "rawCompany": "brightside dental care",
    "linkedinUrl": "https://www.linkedin.com/in/lauren-davies-bb47091b",
    "email": "ldavies@brightsidedentalcare.com",
    "phone": "",
    "city": "Brandon",
    "state": "Manitoba",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_95_opnw",
    "firstName": "Amberene",
    "lastName": "Chunara",
    "title": "Dentist",
    "company": "Harvest Dental Care Calgary",
    "rawCompany": "harvest dental care calgary",
    "linkedinUrl": "https://www.linkedin.com/in/amberene-chunara-5190a9a3",
    "email": "amberene@harvestdental.ca",
    "phone": "",
    "city": "Calgary",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_96_nibb",
    "firstName": "Daniel",
    "lastName": "Hendricks",
    "title": "Dentist",
    "company": "Us Army",
    "rawCompany": "us army",
    "linkedinUrl": "https://www.linkedin.com/in/daniel-hendricks-6b406892",
    "email": "daniel.hendricks@goarmy.com",
    "phone": "",
    "city": "Guelph",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_97_cwd5",
    "firstName": "Rick",
    "lastName": "Grenkow",
    "title": "Dentist",
    "company": "123 Dentist",
    "rawCompany": "123 Dentist",
    "linkedinUrl": "https://www.linkedin.com/in/rick-grenkow-35a19841",
    "email": "rgrenkow@123dentist.com",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_98_kbit",
    "firstName": "Jan",
    "lastName": "Jaffer",
    "title": "Dentist / Owner",
    "company": "Royal Oak Dental",
    "rawCompany": "royal oak dental",
    "linkedinUrl": "https://www.linkedin.com/in/jan-jaffer-5ab70674",
    "email": "jan@royaloakdental.co.nz",
    "phone": "",
    "city": "Calgary",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_99_cxg1",
    "firstName": "Krupal",
    "lastName": "Appalraju",
    "title": "General Dentist",
    "company": "Concept Dental",
    "rawCompany": "concept dental",
    "linkedinUrl": "https://www.linkedin.com/in/krupal-appalraju-9059b380",
    "email": "krupal.appalraju@conceptdental.com.au",
    "phone": "",
    "city": "Red Deer",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_100_pbdq",
    "firstName": "Senia",
    "lastName": "Bobanovic",
    "title": "Dentist",
    "company": "Dentistry At The Heights",
    "rawCompany": "dentistry at the heights",
    "linkedinUrl": "https://www.linkedin.com/in/drseniabobanovic",
    "email": "senia.bobanovic@heightsdentistry.com",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_101_a6f3",
    "firstName": "Barb",
    "lastName": "Luca",
    "title": "Dentist",
    "company": "Royal York Dental",
    "rawCompany": "royal york dental",
    "linkedinUrl": "https://www.linkedin.com/in/barb-luca-429ba5b",
    "email": "barb@royalyorkdental.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_102_2gsw",
    "firstName": "Richard",
    "lastName": "Azzi",
    "title": "Dentist, Owner",
    "company": "Associated Dental Care",
    "rawCompany": "associated dental care",
    "linkedinUrl": "https://www.linkedin.com/in/richard-azzi-5605b474",
    "email": "richard.azzi@associateddentalcare.net",
    "phone": "",
    "city": "Ottawa",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_103_3k7u",
    "firstName": "Fadi",
    "lastName": "Soliman",
    "title": "Dentist",
    "company": "your dental clinic",
    "rawCompany": "ubc",
    "linkedinUrl": "https://www.linkedin.com/in/fadi-soliman-54169351",
    "email": "fadi@discoverunion.org",
    "phone": "",
    "city": "Oakville",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_104_icdp",
    "firstName": "Sal",
    "lastName": "Rashid",
    "title": "Dentist",
    "company": "Dental Choice",
    "rawCompany": "dental choice",
    "linkedinUrl": "https://www.linkedin.com/in/sal-rashid-0a889831",
    "email": "sal@dentalchoice.ca",
    "phone": "",
    "city": "Edmonton",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_105_bezr",
    "firstName": "Tabitha",
    "lastName": "Gervais",
    "title": "Dentist",
    "company": "Boundary Trails Dental Corporation",
    "rawCompany": "boundary trails dental corporation",
    "linkedinUrl": "https://www.linkedin.com/in/tabitha-gervais-57613b30",
    "email": "tabitha@boundarytrails.com",
    "phone": "",
    "city": "",
    "state": "Manitoba",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_106_jn1z",
    "firstName": "Sydney",
    "lastName": "Reyes",
    "title": "Principal Dentist",
    "company": "North Shores Dental",
    "rawCompany": "north shores dental",
    "linkedinUrl": "https://www.linkedin.com/in/sydney-reyes-b6375a23",
    "email": "sydney@northshoresdental.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_107_zsdp",
    "firstName": "Stas",
    "lastName": "Pavlenko",
    "title": "Dentist",
    "company": "Park Dental",
    "rawCompany": "park dental",
    "linkedinUrl": "https://www.linkedin.com/in/stas-pavlenko-1747b886",
    "email": "spavlenko@parkdental.com",
    "phone": "",
    "city": "Edmonton",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_108_7x3t",
    "firstName": "Mariana",
    "lastName": "Williams",
    "title": "Administrator",
    "company": "123 Dentist",
    "rawCompany": "123 Dentist",
    "linkedinUrl": "https://www.linkedin.com/in/mariana-williams-469a9aa",
    "email": "mwilliams@123dentist.com",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_109_pg4u",
    "firstName": "Dave",
    "lastName": "Reynolds",
    "title": "Associate Dentist",
    "company": "Riveredge Dental",
    "rawCompany": "riveredge dental",
    "linkedinUrl": "https://www.linkedin.com/in/dave-reynolds-2621844b",
    "email": "dreynolds@riveredgedental.ca",
    "phone": "",
    "city": "Guelph",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_110_3nke",
    "firstName": "Jodi",
    "lastName": "Monaghan",
    "title": "General Dentist",
    "company": "Dental Choice",
    "rawCompany": "dental choice",
    "linkedinUrl": "https://www.linkedin.com/in/jodi-monaghan-ab789731",
    "email": "jodim@dentalchoice.ca",
    "phone": "",
    "city": "",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_111_fw2e",
    "firstName": "Karen",
    "lastName": "Bai",
    "title": "Principal Dentist",
    "company": "Karen Dental",
    "rawCompany": "karen dental",
    "linkedinUrl": "https://www.linkedin.com/in/karen-bai-5a66336b",
    "email": "karen@karendental.com",
    "phone": "",
    "city": "Mississauga",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_112_j8xl",
    "firstName": "Kristina",
    "lastName": "Mckenzie",
    "title": "Dentist",
    "company": "Awsn",
    "rawCompany": "awsn",
    "linkedinUrl": "https://www.linkedin.com/in/kristina-mckenzie-68815295",
    "email": "kmckenzie@awsn.org",
    "phone": "",
    "city": "Saint Albert",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_113_pm4k",
    "firstName": "Lindsay",
    "lastName": "Louwagie",
    "title": "Associate Dentist",
    "company": "Toothworks Canada",
    "rawCompany": "toothworks canada",
    "linkedinUrl": "https://www.linkedin.com/in/lindsay-louwagie-072398104",
    "email": "lindsay@toothworks.com",
    "phone": "",
    "city": "Toronto",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295715_114_q4t3",
    "firstName": "Ali",
    "lastName": "Rabahi",
    "title": "Dentist",
    "company": "Fine Touch Dental",
    "rawCompany": "fine touch dental",
    "linkedinUrl": "https://www.linkedin.com/in/ali-rabahi-4b813271",
    "email": "ar@finetouchdental.com",
    "phone": "",
    "city": "Halifax Regional Municipality",
    "state": "Nova Scotia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295716_115_83z4",
    "firstName": "Shikhar",
    "lastName": "Saxena",
    "title": "Associate Dentist",
    "company": "Trinity Family Dental",
    "rawCompany": "trinity family dental",
    "linkedinUrl": "https://www.linkedin.com/in/shikhar-saxena-5989298",
    "email": "shikhar.saxena@trinityfamilydentistry.com",
    "phone": "",
    "city": "Belleville",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295716_116_x76u",
    "firstName": "Derek",
    "lastName": "Clease",
    "title": "Dentist",
    "company": "Vancouver Dental Spa",
    "rawCompany": "vancouver dental spa",
    "linkedinUrl": "https://www.linkedin.com/in/derek-clease-11490940",
    "email": "derek@vancouverdentalspa.com",
    "phone": "",
    "city": "Vancouver",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295716_117_a1lm",
    "firstName": "Andrew",
    "lastName": "Rewa",
    "title": "Dentist",
    "company": "Family Care Dental",
    "rawCompany": "family care dental",
    "linkedinUrl": "https://www.linkedin.com/in/andrew-rewa-24b7137b",
    "email": "andrew_rewa@familycaredental.com",
    "phone": "",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295716_118_jqkz",
    "firstName": "John",
    "lastName": "Rush",
    "title": "Dentist",
    "company": "Ottawa Heritage Dental  Kitchener Ontario",
    "rawCompany": "ottawa heritage dental  kitchener ontario",
    "linkedinUrl": "https://www.linkedin.com/in/dr-john-rush-8531001a",
    "email": "jrush@ottawaheritagedental.ca",
    "phone": "",
    "city": "Kitchener",
    "state": "Ontario",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295716_119_7ni2",
    "firstName": "Jennifer",
    "lastName": "Slon",
    "title": "Dentist",
    "company": "Carrefour Dentaire De Montreal",
    "rawCompany": "carrefour dentaire de montreal",
    "linkedinUrl": "https://www.linkedin.com/in/jennifer-slon-a7173052",
    "email": "jennifer.slon@carrefourdentaire.com",
    "phone": "",
    "city": "Montreal",
    "state": "Quebec",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295716_120_kvqc",
    "firstName": "Stevenson",
    "lastName": "Care",
    "title": "Dentist",
    "company": "Stevenson Dental Care",
    "rawCompany": "stevenson dental care",
    "linkedinUrl": "https://www.linkedin.com/in/stevenson-dental-care-25a957b7",
    "email": "care@stevensondental.com",
    "phone": "",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295716_121_amfy",
    "firstName": "April",
    "lastName": "Kanash",
    "title": "Cosmetic Dentist",
    "company": "Beaming White",
    "rawCompany": "beaming white",
    "linkedinUrl": "https://www.linkedin.com/in/april-kanash-9b62734b",
    "email": "april.kanash@beamingwhite.biz",
    "phone": "",
    "city": "Edmonton",
    "state": "Alberta",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295716_122_mo9f",
    "firstName": "Sapna",
    "lastName": "Bhagria",
    "title": "Rdh",
    "company": "123 Dentist",
    "rawCompany": "123 dentist",
    "linkedinUrl": "https://www.linkedin.com/in/sapna-bhagria-938808ab",
    "email": "sbhagria@123dentist.com",
    "phone": "",
    "city": "Langley",
    "state": "British Columbia",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  },
  {
    "id": "lead_1787225295716_123_xqmj",
    "firstName": "Jodi",
    "lastName": "Gergely",
    "title": "Dentist",
    "company": "Royal Oak Dental",
    "rawCompany": "royal oak dental",
    "linkedinUrl": "https://www.linkedin.com/in/jodi-gergely-41551b5b",
    "email": "jgergely@royaloakdental.co.nz",
    "phone": "",
    "city": "",
    "state": "",
    "country": "Canada",
    "status": "pending",
    "sentAt": null,
    "error": null
  }
];
if (typeof module !== 'undefined' && module.exports) { module.exports = { DENTIST_LEADS_PRESET }; }
